version: '3.8'

services:
  app:
    build: .
    container_name: lamp-app
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    networks:
      - lampnet

  db:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - lampnet

networks:
  lampnet:
    driver: bridge
